name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: chmod +x ./build.sh && ./build.sh

    - name: Deploy
      run: |-
        git add -A
        git commit -m "build:auto build and deploy"
        git push
      
