name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy
      run: |-
        git config --global user.email "lovelvqingqing@gmail.com"
        git config --global user.name "Dable Lv"
        git add -A
        git commit -m "build:auto build and deploy"

        echo token:${{secrets.ACCESS_TOKEN}}
        echo "start push"
        git push https://${{secrets.ACCESS_TOKEN}}@github.com/dablelv/backend-cmd.git
